language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

before_script:
  # Make sure the locales used in the tests are installed
  - composer update --ignore-platform-req=php
  - sudo locale-gen en_GB
  - sudo locale-gen en_GB.utf8
  - sudo locale-gen fr_FR
  - sudo locale-gen fr_FR@euro
  - sudo locale-gen fr_FR.utf8

script:
  - tools/phpunit
  - tools/phptal_lint.php -e html tests/input/phptal*.html
